#!/usr/bin/env node

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'fs';
import * as path from 'path';

const SOURCE_PREFIXES = ['CaseDb', 'SeqDb', 'OmopDb'] as const;
const TARGET_PREFIX = 'CommonDb';
const COMMON_API_FILE = path.join('src', 'api.ts');
const GENERATED_FILE_HEADER = `/* eslint-disable */
// @ts-nocheck
/**
 * Generated by @gen-epix/generate-common-api.
 * Do not edit this file manually.
 */
`;

interface BaseDeclaration {
  dependencies: Set<string>;
  kind: DeclarationKind;
  name: string;
  order: number;
}
interface CliArguments {
  caseDbApiFolder: string;
  commonDbApiFolder: string;
  omopDbApiFolder: string;
  seqDbApiFolder: string;
}

type CommonDeclaration = CommonEnumDeclaration | CommonInterfaceDeclaration | CommonTypeDeclaration;

interface CommonEnumDeclaration {
  dependencies: Set<string>;
  entries: EnumEntry[];
  kind: 'enum';
  name: string;
  order: number;
}

interface CommonInterfaceDeclaration {
  dependencies: Set<string>;
  kind: 'interface';
  name: string;
  order: number;
  properties: ParsedProperty[];
}

interface CommonTypeDeclaration {
  dependencies: Set<string>;
  kind: 'type';
  name: string;
  order: number;
  originalType: string;
}

type DeclarationKind = 'enum' | 'interface' | 'type';

interface EnumEntry {
  key: string;
  value: string;
}

interface ParsedApiFile {
  declarations: Map<string, ParsedDeclaration>;
  orderedNames: string[];
}

type ParsedDeclaration = ParsedEnumDeclaration | ParsedInterfaceDeclaration | ParsedTypeDeclaration;

interface ParsedEnumDeclaration extends BaseDeclaration {
  entries: EnumEntry[];
  kind: 'enum';
}

interface ParsedInterfaceDeclaration extends BaseDeclaration {
  kind: 'interface';
  properties: ParsedProperty[];
}

interface ParsedProperty {
  dependencies: Set<string>;
  name: string;
  normalizedType: string;
  optional: boolean;
  originalType: string;
}

interface ParsedTypeDeclaration extends BaseDeclaration {
  kind: 'type';
  normalizedType: string;
  originalType: string;
}

type SourcePrefix = typeof SOURCE_PREFIXES[number];

const parseArguments = (): CliArguments => {
  const [caseDbApiFolder, seqDbApiFolder, omopDbApiFolder, commonDbApiFolder] = process.argv.slice(2);

  if (!caseDbApiFolder || !seqDbApiFolder || !omopDbApiFolder || !commonDbApiFolder) {
    console.error('Usage: generate-common-api <casedb-api-folder> <seqdb-api-folder> <omopdb-api-folder> <commondb-api-folder>');
    process.exit(1);
  }

  return {
    caseDbApiFolder: path.resolve(caseDbApiFolder),
    commonDbApiFolder: path.resolve(commonDbApiFolder),
    omopDbApiFolder: path.resolve(omopDbApiFolder),
    seqDbApiFolder: path.resolve(seqDbApiFolder),
  };
};

const resolveApiTsPath = (apiFolder: string): string => {
  const apiTsPath = path.join(apiFolder, COMMON_API_FILE);

  if (!existsSync(apiTsPath)) {
    console.error(`Expected API file at ${apiTsPath}`);
    process.exit(1);
  }

  return apiTsPath;
};

const skipQuotedString = (value: string, startIndex: number): number => {
  const quote = value[startIndex];

  for (let index = startIndex + 1; index < value.length; index++) {
    if (value[index] === '\\') {
      index++;
      continue;
    }

    if (value[index] === quote) {
      return index;
    }
  }

  throw new Error(`Unterminated string starting at index ${startIndex}`);
};

const skipBlockComment = (value: string, startIndex: number): number => {
  const endIndex = value.indexOf('*/', startIndex + 2);

  if (endIndex === -1) {
    throw new Error(`Unterminated block comment starting at index ${startIndex}`);
  }

  return endIndex + 1;
};

const skipLineComment = (value: string, startIndex: number): number => {
  const endIndex = value.indexOf('\n', startIndex + 2);
  return endIndex === -1 ? value.length - 1 : endIndex;
};

const findMatchingDelimiter = (value: string, startIndex: number, openChar: string, closeChar: string): number => {
  let depth = 0;

  for (let index = startIndex; index < value.length; index++) {
    const char = value[index];
    const nextChar = value[index + 1];

    if (char === '/' && nextChar === '*') {
      index = skipBlockComment(value, index);
      continue;
    }

    if (char === '/' && nextChar === '/') {
      index = skipLineComment(value, index);
      continue;
    }

    if (char === '\'' || char === '"' || char === '`') {
      index = skipQuotedString(value, index);
      continue;
    }

    if (char === openChar) {
      depth++;
      continue;
    }

    if (char === closeChar) {
      depth--;

      if (depth === 0) {
        return index;
      }
    }
  }

  throw new Error(`Unable to find matching ${closeChar} for ${openChar} at index ${startIndex}`);
};

const findTopLevelCharacter = (value: string, targetChar: string): number => {
  let curlyDepth = 0;
  let roundDepth = 0;
  let squareDepth = 0;

  for (let index = 0; index < value.length; index++) {
    const char = value[index];
    const nextChar = value[index + 1];

    if (char === '/' && nextChar === '*') {
      index = skipBlockComment(value, index);
      continue;
    }

    if (char === '/' && nextChar === '/') {
      index = skipLineComment(value, index);
      continue;
    }

    if (char === '\'' || char === '"' || char === '`') {
      index = skipQuotedString(value, index);
      continue;
    }

    if (char === '{') {
      curlyDepth++;
      continue;
    }

    if (char === '}') {
      curlyDepth--;
      continue;
    }

    if (char === '(') {
      roundDepth++;
      continue;
    }

    if (char === ')') {
      roundDepth--;
      continue;
    }

    if (char === '[') {
      squareDepth++;
      continue;
    }

    if (char === ']') {
      squareDepth--;
      continue;
    }

    if (char === targetChar && curlyDepth === 0 && roundDepth === 0 && squareDepth === 0) {
      return index;
    }
  }

  return -1;
};

const findStatementTerminator = (value: string, startIndex: number): number => {
  let curlyDepth = 0;
  let roundDepth = 0;
  let squareDepth = 0;

  for (let index = startIndex; index < value.length; index++) {
    const char = value[index];
    const nextChar = value[index + 1];

    if (char === '/' && nextChar === '*') {
      index = skipBlockComment(value, index);
      continue;
    }

    if (char === '/' && nextChar === '/') {
      index = skipLineComment(value, index);
      continue;
    }

    if (char === '\'' || char === '"' || char === '`') {
      index = skipQuotedString(value, index);
      continue;
    }

    if (char === '{') {
      curlyDepth++;
      continue;
    }

    if (char === '}') {
      curlyDepth--;
      continue;
    }

    if (char === '(') {
      roundDepth++;
      continue;
    }

    if (char === ')') {
      roundDepth--;
      continue;
    }

    if (char === '[') {
      squareDepth++;
      continue;
    }

    if (char === ']') {
      squareDepth--;
      continue;
    }

    if (char === ';' && curlyDepth === 0 && roundDepth === 0 && squareDepth === 0) {
      return index;
    }
  }

  throw new Error(`Unable to find a statement terminator from index ${startIndex}`);
};

const splitTopLevel = (value: string, delimiter: string): string[] => {
  const parts: string[] = [];
  let curlyDepth = 0;
  let roundDepth = 0;
  let squareDepth = 0;
  let segmentStart = 0;

  for (let index = 0; index < value.length; index++) {
    const char = value[index];
    const nextChar = value[index + 1];

    if (char === '/' && nextChar === '*') {
      index = skipBlockComment(value, index);
      continue;
    }

    if (char === '/' && nextChar === '/') {
      index = skipLineComment(value, index);
      continue;
    }

    if (char === '\'' || char === '"' || char === '`') {
      index = skipQuotedString(value, index);
      continue;
    }

    if (char === '{') {
      curlyDepth++;
      continue;
    }

    if (char === '}') {
      curlyDepth--;
      continue;
    }

    if (char === '(') {
      roundDepth++;
      continue;
    }

    if (char === ')') {
      roundDepth--;
      continue;
    }

    if (char === '[') {
      squareDepth++;
      continue;
    }

    if (char === ']') {
      squareDepth--;
      continue;
    }

    if (char === delimiter && curlyDepth === 0 && roundDepth === 0 && squareDepth === 0) {
      parts.push(value.slice(segmentStart, index));
      segmentStart = index + 1;
    }
  }

  parts.push(value.slice(segmentStart));
  return parts;
};

const stripLeadingComments = (value: string): string => {
  let remaining = value.trimStart();

  while (remaining.startsWith('/*') || remaining.startsWith('//')) {
    if (remaining.startsWith('/*')) {
      const endIndex = remaining.indexOf('*/');

      if (endIndex === -1) {
        break;
      }

      remaining = remaining.slice(endIndex + 2).trimStart();
      continue;
    }

    const newlineIndex = remaining.indexOf('\n');
    remaining = newlineIndex === -1 ? '' : remaining.slice(newlineIndex + 1).trimStart();
  }

  return remaining;
};

const stripSourcePrefixes = (value: string): string => value.replace(/\b(?:CaseDb|SeqDb|OmopDb)([A-Z][A-Za-z0-9_]*)\b/g, '$1');

const normalizeType = (value: string): string => stripSourcePrefixes(value)
  .replace(/\r\n?/g, '\n')
  .replace(/\s+/g, ' ')
  .replace(/\s*([<>{}\[\](),|&?:;=])\s*/g, '$1')
  .trim();

const extractDependencies = (value: string): Set<string> => {
  const dependencies = new Set<string>();

  for (const match of value.matchAll(/\b(?:CaseDb|SeqDb|OmopDb)([A-Z][A-Za-z0-9_]*)\b/g)) {
    dependencies.add(match[1]);
  }

  return dependencies;
};

const renderCommonType = (value: string): string => value.replace(/\b(?:CaseDb|SeqDb|OmopDb)([A-Z][A-Za-z0-9_]*)\b/g, `${TARGET_PREFIX}$1`);

const parseInterfaceProperties = (body: string): ParsedProperty[] => {
  const properties: ParsedProperty[] = [];

  splitTopLevel(body, ';').forEach(segment => {
    const cleanedSegment = stripLeadingComments(segment).trim();

    if (!cleanedSegment) {
      return;
    }

    const colonIndex = findTopLevelCharacter(cleanedSegment, ':');

    if (colonIndex === -1) {
      return;
    }

    const rawName = cleanedSegment.slice(0, colonIndex).trim();
    const optional = rawName.endsWith('?');
    const name = optional ? rawName.slice(0, -1).trim() : rawName;
    const originalType = cleanedSegment.slice(colonIndex + 1).trim();

    properties.push({
      dependencies: extractDependencies(originalType),
      name,
      normalizedType: normalizeType(originalType),
      optional,
      originalType,
    });
  });

  return properties;
};

const parseEnumEntries = (body: string): EnumEntry[] => {
  const entries: EnumEntry[] = [];

  splitTopLevel(body, ',').forEach(segment => {
    const cleanedSegment = stripLeadingComments(segment).trim();

    if (!cleanedSegment) {
      return;
    }

    const colonIndex = findTopLevelCharacter(cleanedSegment, ':');

    if (colonIndex === -1) {
      return;
    }

    entries.push({
      key: cleanedSegment.slice(0, colonIndex).trim(),
      value: cleanedSegment.slice(colonIndex + 1).trim(),
    });
  });

  return entries;
};

const parseApiDeclarations = (content: string, sourcePrefix: SourcePrefix): ParsedApiFile => {
  const declarations = new Map<string, ParsedDeclaration>();
  const orderedNames: string[] = [];
  const exportRegex = /export\s+(interface|const|type)\s+([A-Za-z0-9_]+)/g;
  let order = 0;

  while (true) {
    const match = exportRegex.exec(content);

    if (!match) {
      break;
    }

    const rawKind = match[1];
    const fullName = match[2];

    if (!fullName.startsWith(sourcePrefix)) {
      continue;
    }

    const name = fullName.slice(sourcePrefix.length);

    if (rawKind === 'interface') {
      const openBraceIndex = content.indexOf('{', exportRegex.lastIndex);
      const closeBraceIndex = findMatchingDelimiter(content, openBraceIndex, '{', '}');
      const body = content.slice(openBraceIndex + 1, closeBraceIndex);

      declarations.set(name, {
        dependencies: new Set<string>(),
        kind: 'interface',
        name,
        order,
        properties: parseInterfaceProperties(body),
      });
      orderedNames.push(name);
      order++;
      exportRegex.lastIndex = closeBraceIndex + 1;
      continue;
    }

    if (rawKind === 'const') {
      const openBraceIndex = content.indexOf('{', exportRegex.lastIndex);
      const closeBraceIndex = findMatchingDelimiter(content, openBraceIndex, '{', '}');
      const statementEndIndex = findStatementTerminator(content, closeBraceIndex + 1);
      const followingContent = content.slice(statementEndIndex + 1);
      const enumTypePattern = new RegExp(`^\\s*export type ${fullName} = typeof ${fullName}\\[keyof typeof ${fullName}\\];`);
      const enumTypeMatch = followingContent.match(enumTypePattern);

      if (!enumTypeMatch) {
        exportRegex.lastIndex = statementEndIndex + 1;
        continue;
      }

      declarations.set(name, {
        dependencies: new Set<string>(),
        entries: parseEnumEntries(content.slice(openBraceIndex + 1, closeBraceIndex)),
        kind: 'enum',
        name,
        order,
      });
      orderedNames.push(name);
      order++;
      exportRegex.lastIndex = statementEndIndex + 1 + enumTypeMatch[0].length;
      continue;
    }

    const equalsIndex = content.indexOf('=', exportRegex.lastIndex);
    const statementEndIndex = findStatementTerminator(content, equalsIndex + 1);
    const originalType = content.slice(equalsIndex + 1, statementEndIndex).trim();

    declarations.set(name, {
      dependencies: extractDependencies(originalType),
      kind: 'type',
      name,
      normalizedType: normalizeType(originalType),
      order,
      originalType,
    });
    orderedNames.push(name);
    order++;
    exportRegex.lastIndex = statementEndIndex + 1;
  }

  return {
    declarations,
    orderedNames,
  };
};

const intersectEnums = (
  first: ParsedEnumDeclaration,
  second: ParsedEnumDeclaration,
  third: ParsedEnumDeclaration,
): CommonEnumDeclaration | null => {
  const secondEntries = new Map(second.entries.map(entry => [entry.key, entry.value]));
  const thirdEntries = new Map(third.entries.map(entry => [entry.key, entry.value]));
  const entries = first.entries.filter(entry => secondEntries.get(entry.key) === entry.value && thirdEntries.get(entry.key) === entry.value);

  if (entries.length === 0) {
    return null;
  }

  return {
    dependencies: new Set<string>(),
    entries,
    kind: 'enum',
    name: first.name,
    order: first.order,
  };
};

const intersectInterfaces = (
  first: ParsedInterfaceDeclaration,
  second: ParsedInterfaceDeclaration,
  third: ParsedInterfaceDeclaration,
): CommonInterfaceDeclaration | null => {
  const secondProperties = new Map(second.properties.map(property => [property.name, property]));
  const thirdProperties = new Map(third.properties.map(property => [property.name, property]));
  const properties: ParsedProperty[] = [];
  const dependencies = new Set<string>();

  first.properties.forEach(property => {
    const secondProperty = secondProperties.get(property.name);
    const thirdProperty = thirdProperties.get(property.name);

    if (!secondProperty || !thirdProperty) {
      return;
    }

    if (property.normalizedType !== secondProperty.normalizedType || property.normalizedType !== thirdProperty.normalizedType) {
      return;
    }

    const commonProperty: ParsedProperty = {
      dependencies: new Set<string>([
        ...property.dependencies,
        ...secondProperty.dependencies,
        ...thirdProperty.dependencies,
      ]),
      name: property.name,
      normalizedType: property.normalizedType,
      optional: property.optional || secondProperty.optional || thirdProperty.optional,
      originalType: property.originalType,
    };

    commonProperty.dependencies.forEach(dependency => {
      if (dependency !== first.name) {
        dependencies.add(dependency);
      }
    });

    properties.push(commonProperty);
  });

  if (properties.length === 0) {
    return null;
  }

  return {
    dependencies,
    kind: 'interface',
    name: first.name,
    order: first.order,
    properties,
  };
};

const intersectTypes = (
  first: ParsedTypeDeclaration,
  second: ParsedTypeDeclaration,
  third: ParsedTypeDeclaration,
): CommonTypeDeclaration | null => {
  if (first.normalizedType !== second.normalizedType || first.normalizedType !== third.normalizedType) {
    return null;
  }

  return {
    dependencies: new Set<string>([
      ...first.dependencies,
      ...second.dependencies,
      ...third.dependencies,
    ].filter(dependency => dependency !== first.name)),
    kind: 'type',
    name: first.name,
    order: first.order,
    originalType: first.originalType,
  };
};

const intersectDeclarations = (
  caseDbDeclarations: ParsedApiFile,
  seqDbDeclarations: ParsedApiFile,
  omopDbDeclarations: ParsedApiFile,
): Map<string, CommonDeclaration> => {
  const commonDeclarations = new Map<string, CommonDeclaration>();

  caseDbDeclarations.orderedNames.forEach(name => {
    const caseDbDeclaration = caseDbDeclarations.declarations.get(name);
    const seqDbDeclaration = seqDbDeclarations.declarations.get(name);
    const omopDbDeclaration = omopDbDeclarations.declarations.get(name);

    if (!caseDbDeclaration || !seqDbDeclaration || !omopDbDeclaration) {
      return;
    }

    if (caseDbDeclaration.kind !== seqDbDeclaration.kind || caseDbDeclaration.kind !== omopDbDeclaration.kind) {
      return;
    }

    let commonDeclaration: CommonDeclaration | null = null;

    switch (caseDbDeclaration.kind) {
      case 'enum':
        commonDeclaration = intersectEnums(caseDbDeclaration, seqDbDeclaration as ParsedEnumDeclaration, omopDbDeclaration as ParsedEnumDeclaration);
        break;
      case 'interface':
        commonDeclaration = intersectInterfaces(caseDbDeclaration, seqDbDeclaration as ParsedInterfaceDeclaration, omopDbDeclaration as ParsedInterfaceDeclaration);
        break;
      case 'type':
        commonDeclaration = intersectTypes(caseDbDeclaration, seqDbDeclaration as ParsedTypeDeclaration, omopDbDeclaration as ParsedTypeDeclaration);
        break;
      default:
        break;
    }

    if (commonDeclaration) {
      commonDeclarations.set(name, commonDeclaration);
    }
  });

  return commonDeclarations;
};

const retainResolvableDeclarations = (declarations: Map<string, CommonDeclaration>): CommonDeclaration[] => {
  const retainedDeclarations = new Map(declarations);
  let hasChanges = true;

  while (hasChanges) {
    hasChanges = false;

    retainedDeclarations.forEach((declaration, name) => {
      const hasMissingDependency = Array.from(declaration.dependencies).some(dependency => !retainedDeclarations.has(dependency));

      if (hasMissingDependency) {
        retainedDeclarations.delete(name);
        hasChanges = true;
      }
    });
  }

  return Array.from(retainedDeclarations.values()).sort((left, right) => left.order - right.order);
};

const renderDeclaration = (declaration: CommonDeclaration): string => {
  if (declaration.kind === 'enum') {
    const commonName = `${TARGET_PREFIX}${declaration.name}`;
    const entries = declaration.entries.map(entry => `  ${entry.key}: ${entry.value},`).join('\n');

    return `export const ${commonName} = {\n${entries}\n} as const;\n\nexport type ${commonName} = typeof ${commonName}[keyof typeof ${commonName}];`;
  }

  if (declaration.kind === 'type') {
    return `export type ${TARGET_PREFIX}${declaration.name} = ${renderCommonType(declaration.originalType)};`;
  }

  const properties = declaration.properties.map(property => `  ${property.name}${property.optional ? '?' : ''}: ${renderCommonType(property.originalType)};`).join('\n');

  return `export interface ${TARGET_PREFIX}${declaration.name} {\n${properties}\n}`;
};

const renderCommonApiFile = (declarations: CommonDeclaration[]): string => {
  if (declarations.length === 0) {
    return `${GENERATED_FILE_HEADER}\nexport {};\n`;
  }

  return `${GENERATED_FILE_HEADER}\n${declarations.map(renderDeclaration).join('\n\n\n')}\n`;
};

const countDeclarationsByKind = (declarations: CommonDeclaration[]) => declarations.reduce((counts, declaration) => {
  counts[declaration.kind]++;
  return counts;
}, {
  enum: 0,
  interface: 0,
  type: 0,
});

const main = () => {
  const arguments_ = parseArguments();
  const caseDbApiTsPath = resolveApiTsPath(arguments_.caseDbApiFolder);
  const seqDbApiTsPath = resolveApiTsPath(arguments_.seqDbApiFolder);
  const omopDbApiTsPath = resolveApiTsPath(arguments_.omopDbApiFolder);
  const commonDbApiTsPath = path.join(arguments_.commonDbApiFolder, COMMON_API_FILE);
  const commonDbSrcFolder = path.dirname(commonDbApiTsPath);

  const caseDbDeclarations = parseApiDeclarations(readFileSync(caseDbApiTsPath, 'utf-8'), 'CaseDb');
  const seqDbDeclarations = parseApiDeclarations(readFileSync(seqDbApiTsPath, 'utf-8'), 'SeqDb');
  const omopDbDeclarations = parseApiDeclarations(readFileSync(omopDbApiTsPath, 'utf-8'), 'OmopDb');
  const commonDeclarations = retainResolvableDeclarations(intersectDeclarations(caseDbDeclarations, seqDbDeclarations, omopDbDeclarations));
  const counts = countDeclarationsByKind(commonDeclarations);

  mkdirSync(commonDbSrcFolder, { recursive: true });
  writeFileSync(commonDbApiTsPath, renderCommonApiFile(commonDeclarations), 'utf-8');

  console.log(`Wrote ${commonDeclarations.length} common declarations to ${commonDbApiTsPath}`);
  console.log(`Interfaces: ${counts.interface}, types: ${counts.type}, enums: ${counts.enum}`);
};

main();
